export { default as Home } from './index';
export { default as About } from './about';
export { default as Contact } from './contact';
export { default as Career } from './career';
export { default as Services } from './services';
export { default as Booking } from './booking';
export { default as Referee } from './referee';
export { default as JobApplication } from './application';
export { default as NotFound } from './notFound';